### ISSUE TITLE
Create first draft of design of landing page

### ISSUE THREAD

**Issue by emilwihlander** [Dsek-LTH/landing-page#14]
Use a wireframe program (e.g. adobe XD) to create a design concept to iterate over which can then be used to implement it as html and css.

**Comment by emilwihlander** [comment]
I've created a simple mock-up of a possible landing page. To colored scribbles are more of a marker of where I'd like more color rather than actual design. I've included both mobile and desktop. Any thoughts?

![mobile](https://user-images.githubusercontent.com/3393586/74987045-9c93f500-543a-11ea-872f-a386f05b9a38.png)
![desktop](https://user-images.githubusercontent.com/3393586/74987047-9d2c8b80-543a-11ea-9d29-1071196bedb4.png)

**Comment by OskarDamkjaer** [comment]
Jag tycker det ser fint ut! Färggrejen i hörnen är rätt fint tycker jag. Vad vill vi det ska stå i lorem ispum? Också, jag hade något minne om autoplayfilmer som på typ https://goteborgsnation.com/

**Comment by emilwihlander** [comment]
> Färggrejen i hörnen är rätt fint tycker jag.

Känner också det, tycker det att man ska använda en ljusare variant av D och C färgerna och lägga lite mer tid på mönstret.

> Vad vill vi det ska stå i lorem ispum?

Tänker att det ska vara en grundläggande beskrivning av vår organisation. Typ börja med "Vi är sektionen på LTH för alla studenter som studerar Datateknik och Information- och kommunikationsteknik..."

> Också, jag hade något minne om autoplayfilmer

Tänker att det är en v2 av frontsidan.
